#!/bin/sh

test ! -z "$REMOTE_USER" || SeeOther /login?ret=/nd

set -- `echo $DOCUMENT_URI | tr '/' ' '`
shift

case "$1" in
	"") ;;
	art)
		shift
		urld="`urldecode $DOCUMENT_URI`"
		Static "../$urld" | Fin
		;;

	*)
		path="`echo $@ | tr ' ' '/'`"
		if test "$1" = "node_modules"; then
			# for when we want to test
			# modified libraries
			Static $path
		else
			Static htdocs/$1
		fi | Fin
		;;
esac

fun() {
	JSB ❓ help "help_show()"
	JSB 📋 stats "modal_open('stats')"
	JSB 👕 equipment "modal_open('equipment')"
	JSB 📦 inventory "sendCmd('inventory')"
	JSB 👁 look "sendCmd('look')"
}

touch $DOCUMENT_ROOT/tmp/full-size
fun >> $DOCUMENT_ROOT/tmp/fun
cat $PWD/htdocs/index.html
