#!/bin/sh

test ! -z "$REMOTE_USER" || SeeOther /login?ret=/nd

set -- `echo $DOCUMENT_URI | tr '/' ' '`
shift

case "$1" in
	"") ;;
	art)
		shift
		urld="`urldecode $DOCUMENT_URI`"
		Static "../$urld" | Fin
		;;

	*)
		path="`echo $@ | tr ' ' '/'`"
		if test "$1" = "node_modules"; then
			# for when we want to test
			# modified libraries
			Static $path
		else
			Static htdocs/$1
		fi | Fin
		;;
esac

fun() {
	JSB ❓ help "help_show()"
	JSB 📋 stats "modal_open('stats')"
	JSB 👕 equipment "modal_open('equipment')"
	JSB 📦 inventory "sendCmd('inventory')"
	JSB 👁 look "sendCmd('look')"
	cat <<!
<div id="directions">
	<div>
		<nd-button hid></nd-button>
		<nd-button onclick="sendCmd('k')">&uarr;</nd-button>
		<nd-button onclick="sendCmd('K')">&nearr;</nd-button>
	</div>
	<div>
		<nd-button onclick="sendCmd('h')">&larr;</nd-button>
		<nd-button hid></nd-button>
		<nd-button onclick="sendCmd('l')">&rarr;</nd-button>
	</div>
	<div>
		<nd-button hid></nd-button>
		<nd-button onclick="sendCmd('j')">&darr;</nd-button>
		<nd-button onclick="sendCmd('J')">&searr;</nd-button>
	</div>
</div>
!
}

touch $DOCUMENT_ROOT/tmp/full-size
fun >> $DOCUMENT_ROOT/tmp/fun
cat $PWD/htdocs/index.html
cat <<!
<style>
`cat styles.css node_modules/@tty-pt/ndc/ndc.css node_modules/@xterm/xterm/css/xterm.css`
</style>
!
