#!/bin/sh

test ! -z "$REMOTE_USER" || SeeOther /login?ret=/nd

set -- `echo $DOCUMENT_URI | tr '/' ' '`
shift

case "$1" in
	"") ;;
	*)
		Fatal 500 "This should be handled by NDC"
		;;
esac

fun() {
	JSB ❓ help "help_show()"
}

touch $DOCUMENT_ROOT/tmp/full-size
fun >> $DOCUMENT_ROOT/tmp/fun
cat $PWD/htdocs/index.html
cat <<!
<link rel="stylesheet" href="/nd/styles.css">
<link rel="stylesheet" href="/nd/node_modules/@tty-pt/ndc/htdocs/ndc.css">
<link rel="stylesheet" href="/nd/node_modules/@xterm/xterm/css/xterm.css">
!
